version: "3.4"

services:
  influxdb:
    image: influxdb:1.7.9
    container_name: influxdb
    restart: on-failure:2
    ports:
      - "8086:8086"
    networks:
    - backend
    volumes:
      - /srv/metrics-data/monitoring/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB="cadvisor"
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_ADMIN_PASSWORD}

  cadvisor:
    image: google/cadvisor:v0.33.0
    container_name: cadvisor
    restart: on-failure:5
    links:
      - influxdb:srv-influxdb
    command: -storage_driver=influxdb -storage_driver_db=cadvisor -storage_driver_host=srv-influxdb:8086
    ports:
      - "8080:8080"
    networks:
    - frontend
    - backend
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker
      - /srv/metrics-env/monitoring/provisioning/cadvisor:/etc/cadvisor

  grafana:
    image: grafana/grafana:6.5.0
    container_name: grafana
    user: "0"
    restart: on-failure:5
    links:
      - influxdb:srv-influxdb
      - cadvisor:srv-cadvisor
    ports:
      - 3000:3000
    networks:
    - backend
    - frontend
    command: dockerize -wait tcp://influxdb:8086 -wait tcp://cadvisor:8080
    volumes:
      - /srv/metrics-data/monitoring/grafana/data:/var/lib/grafana
      - /srv/metrics-data/monitoring/grafana/dashboards:/var/lib/grafana/dashboards
      - /srv/metrics-env/monitoring/provisioning/grafana:/etc/grafana/provisioning/
      - /srv/metrics-env/monitoring/provisioning/grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}
      - INFLUXDB_ADMIN_USER=${INFLUXDB_ADMIN_USER}

networks:
  backend:
    internal: true
  frontend:
    driver: bridge
